version: '3'
services:
  postgres_db:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - db_nw
    container_name: postgres_db
  app:
    restart: always
    build: .
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    networks:
      - db_nw
    container_name: app
networks:
  db_nw:
    driver: bridge
